name: Agent_DD
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.12.11
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - bigtree==0.29.2
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - chromadb==1.0.15
      - click==8.2.1
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - durationpy==0.10
      - fastapi==0.116.1
      - ffmpy==0.6.0
      - filelock==3.18.0
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - google-ai-generativelanguage==0.6.18
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-genai==1.25.0
      - googleapis-common-protos==1.70.0
      - gradio==5.34.1
      - gradio-client==1.10.3
      - greenlet==3.2.3
      - groovy==0.1.2
      - grpcio==1.73.1
      - grpcio-status==1.73.1
      - h11==0.16.0
      - h5netcdf==1.6.3
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.33.4
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - kubernetes==33.1.0
      - langchain==0.3.25
      - langchain-community==0.3.24
      - langchain-core==0.3.63
      - langchain-google-genai==2.1.5
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.43
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - numpy==2.3.1
      - oauthlib==3.3.1
      - onnxruntime==1.22.1
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-otlp-proto-common==1.35.0
      - opentelemetry-exporter-otlp-proto-grpc==1.35.0
      - opentelemetry-proto==1.35.0
      - opentelemetry-sdk==1.35.0
      - opentelemetry-semantic-conventions==0.56b0
      - orjson==3.11.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.1
      - pillow==11.3.0
      - posthog==5.4.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydmd==2025.5.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - ruff==0.12.3
      - safehttpx==0.1.6
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - starlette==0.47.1
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - xarray==2025.7.1
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.23.0
